name: seb_main_007        
on:                            
  push:
    branches:
      - main                        
jobs:                         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. 
        uses: actions/checkout@v3
      
      - name: Check Node v          
        run: node -v
        
      - name: Install dependencies   
        run: npm install
        working-directory: ./client
      
      - name: Generate build          
        run: npm run build
        working-directory: ./client
      
      - name: Deploy                 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VITE_API: ${{ secrets.VITE_API }}
          VITE_KAKAO_API: ${{ secrets.VITE_KAKAO_API }}
          VITE_DUST_SERVICEKEY: ${{ secrets.VITE_DUST_SERVICEKEY }}
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            dist s3://ourecostory \
            --delete
        working-directory: ./client
        
